### ISSUE TITLE
Protector of the People has incorrect displayid

### ISSUE THREAD

**Issue by Dovvah** [GrenderG/alpha-core#5]
In westfall, standing behind the vendor carts http://puu.sh/FyNoQ/e500e2ab2d.jpg

**Comment by GrenderG** [comment]
That was fixed yesterday in https://github.com/GrenderG/alpha-core/commit/5b42007c3d938c59153fa8ed1d4faf224a79226c. He was removed because he was not present in 0.5.3.

**Comment by Daribon** [comment]
Ain't supposed to be a NPC there to begin with, not even one there in classic.
Reason why vmangos has one there, is because some horde probably did the sniffing and accidentally spawned a guard.

**Comment by GrenderG** [comment]
> Ain't supposed to be a NPC there to begin with, not even one there in classic.
> Reason why vmangos has one there, is because some horde probably did the sniffing and accidentally spawned a guard.

Interesting, didn't know that. Pinging @ratkosrb
